DROP TABLE IF EXISTS user_spells;
DROP TABLE IF EXISTS user_heros;
DROP TABLE IF EXISTS deck_spells;
DROP TABLE IF EXISTS deck_heros;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS spells;
DROP TABLE IF EXISTS heros;
DROP TABLE IF EXISTS users;
